repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      # Run the linter & fix issues
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format
